import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Demopedia | countries population statistics</title>
        <meta name="description" content="Generated by Bertrand" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello world</h1>
      </main>
      <footer />
    </div>
  )
}