import Navbar from '../components/NavBar'
import Head from 'next/head'

export default function Layout({ children }) {
  return (
    <div>
      <Head>
        <title>Demopedia | countries population statistics</title>
        <meta name="description" content="Generated by Bertrand" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-50 h-screen over-flow-auto">
        <Navbar />
        <main className="px-[3rem] pt-2 pb-10">{children}</main>
        <footer />
      </div>
    </div>
  )
}
